name: Build Desktop App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      working-directory: ./apps/embrel-desktop
      run: |
        npm install -g npm@latest
        npm ci
      
    - name: Build Windows executable
      working-directory: ./apps/embrel-desktop
      env:
        USE_HARD_LINKS: false
      run: |
        npm config set script-shell "C:\\Windows\\System32\\cmd.exe"
        npm run dist:win
      
    - name: Upload Windows artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: apps/embrel-desktop/release/*.exe
